services:
  db:
    image: mariadb:11.8-noble
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp-network

  wordpress:
    image: wordpress:6.8.3-php8.3-fpm-alpine
    container_name: wordpress
    depends_on:
      - db
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wp_data:/var/www/html
    networks:
      - wp-network

  phpmyadmin:
    image: phpmyadmin:5.2.3-fpm-alpine
    container_name: phpmyadmin
    depends_on:
      - db
    restart: always
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
    volumes:
      - pma_data:/var/www/html  # 🔥 propre volume phpMyAdmin
    networks:
      - wp-network

  nginx:
    image: nginx:1.28.0-alpine3.21
    container_name: nginx
    depends_on:
      - wordpress
      - phpmyadmin
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - wp_data:/var/www/html/wordpress
      - pma_data:/var/www/html/phpmyadmin  # 🔥 montage explicite
    networks:
      - wp-network

volumes:
  db_data:
  wp_data:
  pma_data:

networks:
  wp-network:
